/**
  ******************************************************************************
  * @file           : image_id.c
  * @brief          : Application image identification footer.
  *                   Placed in its own linker section (.freejoy_id) so the
  *                   configurator's flasher can locate it in the linked .bin
  *                   and verify board match + display target firmware version
  *                   before flashing. Issue anpeaco/FreeJoyX#23.
  ******************************************************************************
  */

#include "image_id.h"
#include "common_defines.h"   /* FIRMWARE_VERSION, BOARD_ID (via board_config.h) */
#include "build_info.h"       /* FIRMWARE_BUILD_ID (auto-generated by Makefile) */

const freejoy_image_id_t freejoy_image_id
    __attribute__((used, section(".freejoy_id"))) = {
        .magic       = FREEJOY_IMAGE_MAGIC,
        .struct_size = sizeof(freejoy_image_id_t),
        .board_id    = BOARD_ID,
        .fw_version  = FIRMWARE_VERSION,
        .build_id    = FIRMWARE_BUILD_ID,
        .reserved    = { 0, 0, 0, 0 },
    };
